-- Create kpi_summary table for Vedavathi Dashboard
-- Run this in your InsForge backend using the SQL runner

-- Drop table if exists (for fresh install)
DROP TABLE IF EXISTS kpi_summary CASCADE;

-- Create kpi_summary table
CREATE TABLE kpi_summary (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module VARCHAR(100) NOT NULL,
    kpi_name VARCHAR(255) NOT NULL,
    kpi_value NUMERIC(15, 2) DEFAULT 0,
    unit VARCHAR(50) DEFAULT 'count',
    trend VARCHAR(20) DEFAULT 'stable',  -- 'up', 'down', 'stable'
    trend_change NUMERIC(5, 2) DEFAULT 0,
    last_updated TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS (Row Level Security)
ALTER TABLE kpi_summary ENABLE ROW LEVEL SECURITY;

-- Allow anon access (read)
CREATE POLICY "Allow for all" 
ON read access kpi_summary FOR SELECT 
TO anon, authenticated 
USING (true);

-- Allow authenticated users to insert/update
CREATE POLICY "Allow authenticated insert/update" 
ON kpi_summary FOR ALL 
TO authenticated 
USING (true)
WITH CHECK (true);

-- Insert default KPI data for all modules
INSERT INTO kpi_summary (module, kpi_name, kpi_value, unit, trend, trend_change) VALUES
-- Overview / Dashboard KPIs
('overview', 'Total Modules', 35, 'modules', 'up', 2.0),
('overview', 'Active Users', 0, 'users', 'stable', 0),
('overview', 'Total Records', 0, 'records', 'up', 5.0),

-- Energy Modules
('solar', 'Total Projects', 0, 'projects', 'stable', 0),
('wind', 'Total Projects', 0, 'projects', 'stable', 0),
('hydro', 'Total Projects', 0, 'projects', 'stable', 0),
('biogas', 'Total Projects', 0, 'projects', 'stable', 0),
('hydrogen', 'Total Projects', 0, 'projects', 'stable', 0),
('kinetic', 'Total Projects', 0, 'projects', 'stable', 0),
('grid', 'Total Projects', 0, 'projects', 'stable', 0),

-- Agriculture Modules
('carbon', 'Carbon Credits', 0, 'credits', 'stable', 0),
('paint', 'Paint Batches', 0, 'batches', 'stable', 0),
('tree', 'Trees Planted', 0, 'trees', 'stable', 0),
('vermi', 'Vermicompost Units', 0, 'units', 'stable', 0),
('agri_tourism', 'Tourism Bookings', 0, 'bookings', 'stable', 0),

-- Animal Husbandry
('cattle', 'Total Cattle', 0, 'heads', 'stable', 0),
('poultry', 'Total Birds', 0, 'birds', 'stable', 0),
('aqua', 'Total Fish', 0, 'fish', 'stable', 0),

-- Veterinary
('vet', 'Total Cases', 0, 'cases', 'stable', 0),
('vedic', 'Vedic Treatments', 0, 'treatments', 'stable', 0),

-- Water & Environment
('water', 'Water Sources', 0, 'sources', 'stable', 0),

-- Management Modules
('crm', 'Total Contacts', 0, 'contacts', 'stable', 0),
('hrm', 'Total Employees', 0, 'employees', 'stable', 0),
('inventory', 'Total Items', 0, 'items', 'stable', 0),
('finance', 'Total Transactions', 0, 'transactions', 'stable', 0),
('dms', 'Documents', 0, 'documents', 'stable', 0),
('workflow', 'Active Workflows', 0, 'workflows', 'stable', 0),
('ticketing', 'Open Tickets', 0, 'tickets', 'stable', 0),
('bi', 'Reports', 0, 'reports', 'stable', 0),
('booking', 'Bookings', 0, 'bookings', 'stable', 0),
('lms', 'Courses', 0, 'courses', 'stable', 0),
('fieldService', 'Work Orders', 0, 'orders', 'stable', 0),
('farmer', 'Registered Farmers', 0, 'farmers', 'stable', 0),
('survey', 'Surveys', 0, 'surveys', 'stable', 0),
('schemes', 'Government Schemes', 0, 'schemes', 'stable', 0),

-- Logistics
('logistics', 'Deliveries', 0, 'deliveries', 'stable', 0),
('trust', 'Trust Members', 0, 'members', 'stable', 0),
('command', 'Commands', 0, 'commands', 'stable', 0);

-- Create function to update KPI (for future use)
CREATE OR REPLACE FUNCTION update_kpi(
    p_module VARCHAR,
    p_kpi_name VARCHAR,
    p_value NUMERIC
)
RETURNS VOID AS $$
BEGIN
    UPDATE kpi_summary 
    SET kpi_value = p_value,
        last_updated = NOW()
    WHERE module = p_module AND kpi_name = p_kpi_name;
END;
$$ LANGUAGE plpgsql;

-- Grant execute permission to authenticated users
GRANT EXECUTE ON FUNCTION update_kpi(VARCHAR, VARCHAR, NUMERIC) TO authenticated;

-- Verify table created
SELECT * FROM kpi_summary ORDER BY module, kpi_name LIMIT 10;
