"""
FIX ALL UI/UX ISSUES — Phases 1-5
Phase 1: Add 14 missing onclick functions + 6 missing tab switchers
Phase 2: Re-apply tab overflow CSS fix
Phase 3: Add empty-state CSS
Phase 4: Add loading timeout JS
Phase 5: Add missing utility CSS classes
"""
import re, sys, io, os

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

BASE = r'e:\Vedavathi\dashboard'
JS = os.path.join(BASE, 'app.js')
CSS = os.path.join(BASE, 'index.css')
HTML = os.path.join(BASE, 'index.html')

with open(JS, encoding='utf-8', errors='replace') as f:
    js = f.read()
with open(CSS, encoding='utf-8', errors='replace') as f:
    css = f.read()

# ==================================================================
# PHASE 1: ADD MISSING FUNCTIONS TO app.js
# ==================================================================
print("PHASE 1: Adding missing functions...")

# The universal tab switcher already exists as _universalTab
# We need to add the missing tab functions and form show functions

missing_functions_js = '''

/* ============================================================
   PHASE 1 FIX — Missing Functions (Auto-generated by UI/UX audit)
   ============================================================ */

/* --- Missing Tab Switchers --- */
function bookingTab(pane, btn) {
    _universalTab('.dairy-pane', pane, btn, '.dairy-tab-btn');
}
window.bookingTab = bookingTab;

function fpTab(pane, btn) {
    _universalTab('.dairy-pane', pane, btn, '.dairy-tab-btn');
}
window.fpTab = fpTab;

function fsTab(pane, btn) {
    _universalTab('.dairy-pane', pane, btn, '.dairy-tab-btn');
}
window.fsTab = fsTab;

function lmsTab(pane, btn) {
    _universalTab('.dairy-pane', pane, btn, '.dairy-tab-btn');
}
window.lmsTab = lmsTab;

function surveyTab(pane, btn) {
    _universalTab('.dairy-pane', pane, btn, '.dairy-tab-btn');
}
window.surveyTab = surveyTab;

function schemeTab(pane, btn) {
    _universalTab('.dairy-pane', pane, btn, '.dairy-tab-btn');
}
window.schemeTab = schemeTab;

/* --- Missing Form/Action Functions --- */
function showAddLeadForm() {
    const modal = document.getElementById('add-lead-modal');
    if (modal) { modal.style.display = 'flex'; return; }
    alert('Add Lead form - Coming soon');
}
window.showAddLeadForm = showAddLeadForm;

function showAddEmployeeForm() {
    const modal = document.getElementById('add-employee-modal');
    if (modal) { modal.style.display = 'flex'; return; }
    alert('Add Employee form - Coming soon');
}
window.showAddEmployeeForm = showAddEmployeeForm;

function showLeaveRequestForm() {
    const modal = document.getElementById('leave-request-modal');
    if (modal) { modal.style.display = 'flex'; return; }
    alert('Leave Request form - Coming soon');
}
window.showLeaveRequestForm = showLeaveRequestForm;

function showAddItemForm() {
    const modal = document.getElementById('add-item-modal');
    if (modal) { modal.style.display = 'flex'; return; }
    alert('Add Item form - Coming soon');
}
window.showAddItemForm = showAddItemForm;

function showCreatePOForm() {
    const modal = document.getElementById('create-po-modal');
    if (modal) { modal.style.display = 'flex'; return; }
    alert('Create Purchase Order form - Coming soon');
}
window.showCreatePOForm = showCreatePOForm;

function showCreateInvoice() {
    const modal = document.getElementById('create-invoice-modal');
    if (modal) { modal.style.display = 'flex'; return; }
    alert('Create Invoice form - Coming soon');
}
window.showCreateInvoice = showCreateInvoice;

function filterTasks(status) {
    const container = document.getElementById('page-container');
    if (!container) return;
    const rows = container.querySelectorAll('.task-row, tr[data-status]');
    rows.forEach(r => {
        if (!status || status === 'all') { r.style.display = ''; return; }
        const st = r.getAttribute('data-status') || r.textContent;
        r.style.display = st.toLowerCase().includes(status.toLowerCase()) ? '' : 'none';
    });
}
window.filterTasks = filterTasks;

function filterComms(type) {
    const container = document.getElementById('page-container');
    if (!container) return;
    const rows = container.querySelectorAll('.comm-row, tr[data-type]');
    rows.forEach(r => {
        if (!type || type === 'all') { r.style.display = ''; return; }
        const t = r.getAttribute('data-type') || r.textContent;
        r.style.display = t.toLowerCase().includes(type.toLowerCase()) ? '' : 'none';
    });
}
window.filterComms = filterComms;

/* ============================================================
   PHASE 4 FIX — Loading Timeout (10s) for all "Loading..." texts
   ============================================================ */
(function() {
    setTimeout(function() {
        document.querySelectorAll('p, div, span, td').forEach(function(el) {
            if (el.textContent.match(/^Loading .{2,50}\\.\\.\\./)) {
                if (el.textContent.trim().startsWith('Loading')) {
                    el.innerHTML = '<span style="color:rgba(200,214,229,0.4);font-style:italic">Data unavailable — check connection</span>';
                }
            }
        });
    }, 10000);
})();

/* END PHASE 1 + 4 FIX */
'''

# Check if these functions already exist
fns_to_add = ['bookingTab', 'fpTab', 'fsTab', 'lmsTab', 'surveyTab', 'schemeTab',
              'showAddLeadForm', 'showAddEmployeeForm', 'showLeaveRequestForm',
              'showAddItemForm', 'showCreatePOForm', 'showCreateInvoice',
              'filterTasks', 'filterComms']

already_exist = []
to_add = []
for fn in fns_to_add:
    if f'function {fn}' in js or f'window.{fn}' in js:
        already_exist.append(fn)
    else:
        to_add.append(fn)

print(f"  Already exist: {already_exist}")
print(f"  Need to add: {to_add}")

if to_add:
    # Append to end of app.js
    with open(JS, 'a', encoding='utf-8') as f:
        f.write(missing_functions_js)
    print(f"  Appended {len(to_add)} functions + loading timeout to app.js")
else:
    print("  All functions already exist!")

# ==================================================================
# PHASE 2: RE-APPLY TAB OVERFLOW CSS FIX
# ==================================================================
print("\nPHASE 2: Tab overflow CSS fix...")

# Check if the fix already exists at the end
last_3000 = css[-3000:]
if 'MASTER TAB OVERFLOW FIX' in last_3000:
    print("  Tab overflow fix already present at end of CSS - skipping")
else:
    tab_overflow_css = '''

/* ============================================================
   MASTER TAB OVERFLOW FIX — v6.6.0
   Ensures ALL hub nav bars scroll horizontally
   ============================================================ */

/* Step 1: Constrain parent containers */
.main-content {
    overflow-x: hidden !important;
    max-width: 100vw !important;
}

.page-area {
    overflow-x: hidden !important;
    width: 100% !important;
    max-width: 100% !important;
    box-sizing: border-box !important;
}

#page-container {
    display: block !important;
    width: 100% !important;
    max-width: 100% !important;
    overflow-x: hidden !important;
    overflow-y: visible !important;
    box-sizing: border-box !important;
}

.page-section,
.page-section.active {
    display: block !important;
    width: 100% !important;
    max-width: 100% !important;
    overflow-x: hidden !important;
    overflow-y: visible !important;
    box-sizing: border-box !important;
}

.page-section.active {
    display: block !important;
}

/* Step 2: Make ALL nav variants scrollable */
.dairy-nav,
.vet-nav,
.en-nav,
.crm-nav,
.vermi-nav,
.tree-nav,
.aqua-nav,
.paint-nav,
.biogas-nav,
.wind-nav,
.solar-nav,
.carbon-nav,
.fin-nav,
.trust-nav,
.cmd-nav,
.log-nav,
.water-nav,
.vedic-nav,
.agri-nav,
.hub-nav,
.module-nav,
.tab-nav {
    position: static !important;
    display: flex !important;
    flex-direction: row !important;
    flex-wrap: nowrap !important;
    overflow-x: auto !important;
    overflow-y: hidden !important;
    -webkit-overflow-scrolling: touch !important;
    scroll-behavior: smooth !important;
    gap: 4px !important;
    padding: 8px 16px !important;
    border-bottom: 1px solid rgba(255,255,255,0.07) !important;
    background: rgba(0,0,0,0.15) !important;
    align-items: center !important;
    min-height: 50px !important;
    flex-shrink: 0 !important;
    width: 100% !important;
    max-width: 100% !important;
    min-width: 0 !important;
    box-sizing: border-box !important;
    scrollbar-width: thin !important;
    scrollbar-color: rgba(0,176,255,0.35) transparent !important;
}

/* Thin scrollbar for navs */
.dairy-nav::-webkit-scrollbar,
.vet-nav::-webkit-scrollbar,
.en-nav::-webkit-scrollbar,
.crm-nav::-webkit-scrollbar,
.vermi-nav::-webkit-scrollbar,
.tree-nav::-webkit-scrollbar,
.aqua-nav::-webkit-scrollbar,
.paint-nav::-webkit-scrollbar,
.biogas-nav::-webkit-scrollbar,
.wind-nav::-webkit-scrollbar,
.solar-nav::-webkit-scrollbar,
.carbon-nav::-webkit-scrollbar {
    height: 4px !important;
    display: block !important;
}

.dairy-nav::-webkit-scrollbar-thumb,
.vet-nav::-webkit-scrollbar-thumb,
.en-nav::-webkit-scrollbar-thumb,
.crm-nav::-webkit-scrollbar-thumb,
.vermi-nav::-webkit-scrollbar-thumb,
.tree-nav::-webkit-scrollbar-thumb,
.aqua-nav::-webkit-scrollbar-thumb,
.paint-nav::-webkit-scrollbar-thumb,
.biogas-nav::-webkit-scrollbar-thumb,
.wind-nav::-webkit-scrollbar-thumb,
.solar-nav::-webkit-scrollbar-thumb,
.carbon-nav::-webkit-scrollbar-thumb {
    background: rgba(0,176,255,0.4) !important;
    border-radius: 999px !important;
}

/* Step 3: Tab buttons base style */
.dairy-tab-btn,
.vet-tab-btn,
.en-tbtn,
.crm-tab-btn,
.vermi-tbtn,
.tree-tbtn,
.paint-tab-btn,
.carbon-tab-btn,
.solar-tab-btn,
.hub-more-btn {
    display: inline-flex !important;
    align-items: center !important;
    gap: 5px !important;
    background: transparent !important;
    border: 1px solid rgba(255,255,255,0.08) !important;
    color: rgba(200,214,229,0.7) !important;
    padding: 6px 14px !important;
    border-radius: 8px !important;
    cursor: pointer !important;
    white-space: nowrap !important;
    font-size: 0.78rem !important;
    font-weight: 500 !important;
    font-family: 'Inter','Outfit',sans-serif !important;
    transition: all 0.18s ease !important;
    flex-shrink: 0 !important;
    min-height: 34px !important;
}

.dairy-tab-btn:hover,
.vet-tab-btn:hover,
.en-tbtn:hover,
.crm-tab-btn:hover,
.vermi-tbtn:hover,
.tree-tbtn:hover,
.paint-tab-btn:hover,
.carbon-tab-btn:hover,
.solar-tab-btn:hover {
    background: rgba(255,255,255,0.07) !important;
    color: #e0eaf4 !important;
    border-color: rgba(255,255,255,0.15) !important;
}

.dairy-tab-btn.active,
.vet-tab-btn.active,
.en-tbtn.active,
.crm-tab-btn.active,
.vermi-tbtn.active,
.tree-tbtn.active,
.paint-tab-btn.active,
.carbon-tab-btn.active,
.solar-tab-btn.active {
    background: rgba(0,176,255,0.12) !important;
    color: #42caff !important;
    border-color: rgba(0,176,255,0.3) !important;
    font-weight: 600 !important;
}
'''
    with open(CSS, 'a', encoding='utf-8') as f:
        f.write(tab_overflow_css)
    print("  Appended tab overflow CSS fix")

# ==================================================================
# PHASE 3: ADD EMPTY STATE + FORM + UTILITY CSS
# ==================================================================
print("\nPHASE 3: Adding empty-state, form, utility CSS...")

utility_css = '''

/* ============================================================
   PHASE 3+5: Empty States, Forms, Utilities
   ============================================================ */

/* Empty state */
.empty-state,
tbody:empty::after {
    display: block !important;
    text-align: center !important;
    color: rgba(200,214,229,0.35) !important;
    font-size: 0.85rem !important;
    font-style: italic !important;
    padding: 32px 16px !important;
}

tbody:empty::after {
    content: "No data available" !important;
}

/* Error state */
.error-state {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding: 40px 24px;
    color: rgba(255,82,82,0.7);
    text-align: center;
    gap: 8px;
    font-size: 0.9rem;
}

/* Loading state with spinner */
.loading-state {
    display: flex;
    align-items: center;
    gap: 10px;
    padding: 24px;
    color: rgba(200,214,229,0.5);
    font-size: 0.85rem;
}

.loading-state::before {
    content: '';
    width: 16px;
    height: 16px;
    border: 2px solid rgba(0,176,255,0.2);
    border-top-color: rgba(0,176,255,0.8);
    border-radius: 50%;
    animation: spin 0.8s linear infinite;
    flex-shrink: 0;
}

@keyframes spin {
    to { transform: rotate(360deg); }
}

/* Tooltip */
.tooltip {
    position: relative;
    cursor: help;
}

.tooltip::after {
    content: attr(data-tip);
    position: absolute;
    bottom: calc(100% + 6px);
    left: 50%;
    transform: translateX(-50%) scale(0.95);
    background: #1a2035;
    color: #e0eaf4;
    padding: 6px 12px;
    border-radius: 6px;
    font-size: 0.75rem;
    white-space: nowrap;
    opacity: 0;
    pointer-events: none;
    transition: all 0.15s ease;
    border: 1px solid rgba(255,255,255,0.1);
    z-index: 999;
    box-shadow: 0 4px 16px rgba(0,0,0,0.4);
}

.tooltip:hover::after {
    opacity: 1;
    transform: translateX(-50%) scale(1);
}

/* Dropdown menu */
.dropdown-menu {
    position: absolute;
    top: calc(100% + 4px);
    right: 0;
    background: #1a2035;
    border: 1px solid rgba(255,255,255,0.1);
    border-radius: 10px;
    padding: 6px;
    min-width: 160px;
    z-index: 200;
    box-shadow: 0 8px 32px rgba(0,0,0,0.5);
    display: none;
}

.dropdown-menu.open {
    display: block;
}

.dropdown-menu a,
.dropdown-menu button {
    display: block;
    width: 100%;
    padding: 8px 12px;
    color: rgba(200,214,229,0.8);
    font-size: 0.82rem;
    border: none;
    background: transparent;
    text-align: left;
    border-radius: 6px;
    cursor: pointer;
    transition: background 0.15s ease;
}

.dropdown-menu a:hover,
.dropdown-menu button:hover {
    background: rgba(255,255,255,0.06);
    color: #e0eaf4;
}

/* Form controls for dark theme */
input[type="text"],
input[type="number"],
input[type="date"],
input[type="email"],
input[type="tel"],
input[type="password"],
input[type="search"],
select,
textarea,
.form-control {
    background: rgba(255,255,255,0.04) !important;
    border: 1px solid rgba(255,255,255,0.12) !important;
    border-radius: 8px !important;
    color: #e0eaf4 !important;
    padding: 9px 14px !important;
    font-size: 0.875rem !important;
    font-family: 'Inter',sans-serif !important;
    transition: border-color 0.18s ease, box-shadow 0.18s ease !important;
    outline: none !important;
}

input:focus,
select:focus,
textarea:focus,
.form-control:focus {
    border-color: rgba(0,176,255,0.5) !important;
    box-shadow: 0 0 0 3px rgba(0,176,255,0.12) !important;
    background: rgba(255,255,255,0.06) !important;
}

input::placeholder,
textarea::placeholder {
    color: rgba(200,214,229,0.35) !important;
}

select option {
    background: #1a2035 !important;
    color: #e0eaf4 !important;
}

/* Clickable cursor on all interactive elements */
button,
[role="button"],
[onclick],
.btn,
.clean-btn,
.action-btn,
.kpi-card,
.menu-item,
.menu-group-header,
.alert-btn {
    cursor: pointer !important;
}

/* Sidebar group header */
.menu-group-header {
    cursor: pointer !important;
    user-select: none !important;
    transition: color 0.15s ease, background 0.15s ease !important;
}

.menu-group-header:hover {
    color: rgba(200,214,229,0.85) !important;
    background: rgba(255,255,255,0.04) !important;
}

/* END PHASE 3+5 CSS */
'''

if 'PHASE 3+5' not in css:
    with open(CSS, 'a', encoding='utf-8') as f:
        f.write(utility_css)
    print("  Appended empty-state, form, utility CSS")
else:
    print("  Phase 3+5 CSS already present - skipping")

# ==================================================================
# PHASE VERSION BUMP
# ==================================================================
print("\nBumping versions...")
with open(HTML, encoding='utf-8') as f:
    html_content = f.read()

html_content = re.sub(r'index\.css\?v=[\d.]+', 'index.css?v=6.6.0', html_content)
html_content = re.sub(r'app\.js\?v=[\d.]+', 'app.js?v=6.6.0', html_content)

with open(HTML, 'w', encoding='utf-8') as f:
    f.write(html_content)

print("  Bumped CSS + JS to v6.6.0")

# ==================================================================
# VERIFY
# ==================================================================
print("\n=== VERIFICATION ===")

# Re-read files
with open(JS, encoding='utf-8', errors='replace') as f:
    js2 = f.read()
with open(CSS, encoding='utf-8', errors='replace') as f:
    css2 = f.read()

# Check all functions exist now
all_ok = True
for fn in fns_to_add:
    if f'function {fn}' in js2 or f'window.{fn}' in js2:
        print(f"  OK: {fn}() exists")
    else:
        print(f"  FAIL: {fn}() still missing!")
        all_ok = False

# Check CSS fixes
if 'MASTER TAB OVERFLOW FIX' in css2:
    print("  OK: Tab overflow CSS present")
else:
    print("  FAIL: Tab overflow CSS missing!")
    all_ok = False

if 'empty-state' in css2:
    print("  OK: Empty state CSS present")
else:
    print("  FAIL: Empty state CSS missing!")

if 'error-state' in css2:
    print("  OK: Error state CSS present")
if '.tooltip' in css2:
    print("  OK: Tooltip CSS present")
if '.dropdown-menu' in css2:
    print("  OK: Dropdown menu CSS present")

# Syntax check
print("\nSyntax check...")
os.system(f'node --check "{JS}" 2>&1')

print("\n=== ALL PHASES COMPLETE ===")
